# Generated by Django 5.0 on 2025-11-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Format: 2024-2025', max_length=9, unique=True)),
                ('designation', models.CharField(help_text='Ex: Année académique 2024-2025', max_length=100)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_en_cours', models.BooleanField(default=False, help_text='Marquer comme année en cours')),
            ],
            options={
                'verbose_name': 'Année Académique',
                'verbose_name_plural': 'Années Académiques',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='CategorieEnseignant',
            fields=[
                ('CodeCategorie', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DesignationCategorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: AM, PM, S1, S2', max_length=10, unique=True)),
                ('designation', models.CharField(help_text='Ex: Matinée, Après-midi', max_length=100)),
                ('heure_debut', models.TimeField(help_text='Heure de début (ex: 08:00)')),
                ('heure_fin', models.TimeField(help_text='Heure de fin (ex: 12:00)')),
                ('est_actif', models.BooleanField(default=True, help_text='Créneau actif pour planification')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Créneau',
                'verbose_name_plural': 'Créneaux',
                'ordering': ['ordre', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('CodeFonction', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DesignationFonction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('CodeGrade', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DesignationGrade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('CodeMention', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('DesignationMention', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('CodeNiveau', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('DesignationNiveau', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: B1, A205, AMPHI-A', max_length=20, unique=True)),
                ('designation', models.CharField(help_text='Ex: Salle B1 - Bâtiment Sciences', max_length=200)),
                ('capacite', models.IntegerField(blank=True, help_text='Nombre de places', null=True)),
                ('type_salle', models.CharField(choices=[('TD', 'Salle de TD'), ('TP', 'Salle de TP'), ('AMPHI', 'Amphithéâtre'), ('LAB', 'Laboratoire'), ('AUTRE', 'Autre')], default='TD', max_length=20)),
                ('est_disponible', models.BooleanField(default=True, help_text='Salle disponible pour planification')),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('CodeSection', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('DesignationSection', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('CodeSemestre', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DesignationSemestre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('CodeDept', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('DesignationDept', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='reglage.section')),
            ],
        ),
        migrations.CreateModel(
            name='SemaineCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semaine', models.IntegerField(help_text='Numéro de la semaine (1, 2, 3...)')),
                ('date_debut', models.DateField(help_text='Date de début de la semaine (doit être un LUNDI)')),
                ('date_fin', models.DateField(help_text='Date de fin de la semaine (doit être un SAMEDI)')),
                ('designation', models.CharField(help_text='Ex: Semaine 1 du 1er semestre', max_length=200)),
                ('est_en_cours', models.BooleanField(default=False, help_text='Marquer comme semaine en cours')),
                ('annee_academique', models.CharField(blank=True, help_text='Année académique (ex: 2024-2025)', max_length=9, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Semaine de Cours',
                'verbose_name_plural': 'Semaines de Cours',
                'ordering': ['date_debut'],
                'unique_together': {('numero_semaine', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeClasse', models.CharField(blank=True, max_length=40, unique=True)),
                ('DesignationClasse', models.CharField(blank=True, max_length=200)),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglage.mention')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglage.niveau')),
            ],
            options={
                'unique_together': {('niveau', 'mention')},
            },
        ),
    ]
