# Generated by Django 5.2.8 on 2025-11-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneeacademique',
            options={'ordering': ['-code'], 'verbose_name': 'Année Académique', 'verbose_name_plural': 'Années Académiques'},
        ),
        migrations.AlterModelOptions(
            name='creneau',
            options={'ordering': ['ordre', 'heure_debut'], 'verbose_name': 'Créneau', 'verbose_name_plural': 'Créneaux'},
        ),
        migrations.AlterModelOptions(
            name='salle',
            options={'ordering': ['code'], 'verbose_name': 'Salle', 'verbose_name_plural': 'Salles'},
        ),
        migrations.AlterModelOptions(
            name='semainecours',
            options={'ordering': ['date_debut'], 'verbose_name': 'Semaine de Cours', 'verbose_name_plural': 'Semaines de Cours'},
        ),
        migrations.AlterUniqueTogether(
            name='semainecours',
            unique_together={('numero_semaine', 'annee_academique')},
        ),
    ]
