# Generated by Django 6.0 on 2026-01-02 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0002_alter_anneeacademique_options_alter_creneau_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='reglage.departement'),
        ),
    ]
