# Generated by Django 6.0 on 2026-01-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0003_mention_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='type_creneau',
            field=models.CharField(choices=[('cours', 'Cours'), ('examen', 'Examen'), ('les_deux', 'Cours et Examens')], default='les_deux', help_text="Type d'horaire où ce créneau apparaît", max_length=10),
        ),
    ]
