# Generated by Django 6.0 on 2026-01-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0004_creneau_type_creneau'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='section',
            field=models.ForeignKey(blank=True, help_text="Section pour les créneaux d'examens (laisser vide pour les cours généraux)", null=True, on_delete=django.db.models.deletion.CASCADE, to='reglage.section'),
        ),
    ]
