# Generated by Django 4.2.15 on 2026-02-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0005_creneau_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type_charge', models.CharField(max_length=50, unique=True, verbose_name='Code du type de charge')),
                ('designation_type_charge', models.CharField(max_length=100, verbose_name='Désignation du type de charge')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Type de charge',
                'verbose_name_plural': 'Types de charge',
                'ordering': ['code_type_charge'],
            },
        ),
    ]
