# Generated by Django 4.2.15 on 2026-02-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0007_create_default_type_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100, unique=True, verbose_name='Grade')),
                ('montant_par_heure', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant par heure (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Taux horaire',
                'verbose_name_plural': 'Taux horaires',
                'ordering': ['grade'],
            },
        ),
    ]
