# Generated by Django 4.2.15 on 2026-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0009_create_default_taux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taux',
            name='montant_par_heure',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant par heure ($)'),
        ),
    ]
