# Generated by Django 5.0 on 2025-11-06 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reglage', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatriculeEnseignant', models.CharField(max_length=20)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('Destination', models.CharField(max_length=255)),
                ('Motif', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-Date'],
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('type', models.CharField(choices=[('annonce', 'Annonce'), ('communique', 'Communiqué'), ('evenement', 'Événement'), ('information', 'Information')], default='information', max_length=20, verbose_name='Type')),
                ('cible', models.CharField(choices=[('tous', 'Tous les utilisateurs'), ('enseignants', 'Enseignants seulement'), ('etudiants', 'Étudiants seulement'), ('administratif', 'Personnel administratif')], default='tous', max_length=20, verbose_name='Destiné à')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('important', models.BooleanField(default=False, verbose_name='Important')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='annonces/', verbose_name='Pièce jointe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('publie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_publiees', to='teachers.teacher', verbose_name='Publié par')),
            ],
            options={
                'verbose_name': 'Annonce/Communiqué',
                'verbose_name_plural': 'Annonces et Communiqués',
                'ordering': ['-important', '-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='AutorisationAbsenceEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('motif', models.TextField()),
                ('destination', models.CharField(max_length=255)),
                ('disposition_cours', models.TextField(blank=True)),
                ('disposition_stage', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorisations_absence', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Sexe')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('classe', models.CharField(blank=True, max_length=40, null=True, verbose_name='Classe')),
                ('annee_academique', models.CharField(blank=True, max_length=20, null=True, verbose_name='Année académique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='AutorisationAbsenceEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('motif', models.TextField(verbose_name="Motif de l'absence")),
                ('destination', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destination')),
                ('disposition_cours', models.TextField(blank=True, null=True, verbose_name='Disposition prise pour les cours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('chef_departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorisations_absence_etudiant', to='teachers.teacher', verbose_name='Chef de Département')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_administrative.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': "Autorisation d'absence étudiant",
                'verbose_name_plural': "Autorisations d'absence étudiants",
                'ordering': ['-created_at'],
            },
        ),
    ]
