# Generated by Django 6.0 on 2026-01-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrative', '0002_inscription'),
    ]

    operations = [
    ]
