# Generated by Django 5.0 on 2025-11-06 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reglage', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Libellé du document')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier')),
                ('categorie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie')),
                ('mots_cles', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mots clés')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_entree', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'entrée")),
                ('expediteur', models.CharField(max_length=255, verbose_name='Expéditeur')),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('date_reception', models.DateField(default=django.utils.timezone.now, verbose_name='Date de réception')),
                ('statut', models.CharField(default='Reçu', max_length=50, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('basse', 'Basse')], default='Normal', max_length=20, verbose_name='Priorité')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_entrants', to='reglage.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Document entrant',
                'verbose_name_plural': 'Documents entrants',
                'ordering': ['-date_entree'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSortant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Libellé du document')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier')),
                ('categorie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie')),
                ('mots_cles', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mots clés')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_sortie', models.DateField(default=django.utils.timezone.now, verbose_name='Date de sortie')),
                ('expediteur', models.CharField(max_length=255, verbose_name='Expéditeur')),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('mode_envoi', models.CharField(choices=[('courrier', 'Courrier'), ('email', 'Email'), ('fax', 'Fax'), ('en_personne', 'En personne')], default='Courrier', max_length=50, verbose_name="Mode d'envoi")),
                ('accusé_reception', models.BooleanField(default=False, verbose_name='Accusé de réception reçu')),
                ('date_accuse_reception', models.DateField(blank=True, null=True, verbose_name="Date d'accusé de réception")),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_sortants', to='reglage.departement', verbose_name="Département d'origine")),
                ('redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_rediges', to='teachers.teacher', verbose_name='Rédacteur')),
            ],
            options={
                'verbose_name': 'Document sortant',
                'verbose_name_plural': 'Documents sortants',
                'ordering': ['-date_sortie'],
            },
        ),
    ]
