# Generated by Django 5.0 on 2025-11-06 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire'), ('agent', 'Agent')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Photo de profil')),
                ('matricule_etudiant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricule étudiant')),
                ('classe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Classe')),
                ('matricule_enseignant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricule enseignant')),
                ('departement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Département')),
                ('grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grade')),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Section')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='accounts.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
