# Generated by Django 5.0 on 2025-11-06 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours_Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ue', models.CharField(max_length=20)),
                ('intitule_ue', models.CharField(max_length=255)),
                ('intitule_ec', models.CharField(max_length=255)),
                ('credit', models.IntegerField()),
                ('cmi', models.FloatField()),
                ('td_tp', models.FloatField()),
                ('classe', models.CharField(max_length=50)),
                ('semestre', models.CharField(max_length=20)),
                ('departement', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Cours Attribution',
                'verbose_name_plural': 'Cours Attributions',
            },
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2024-2025', max_length=9, null=True, verbose_name='Année académique')),
                ('type_charge', models.CharField(choices=[('Reguliere', 'Régulière'), ('Supplementaire', 'Supplémentaire')], max_length=15, null=True, verbose_name='Type de charge')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('code_ue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='courses.course', verbose_name='Code UE')),
                ('matricule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', to_field='matricule', verbose_name='Matricule enseignant')),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
                'unique_together': {('matricule', 'code_ue', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=9)),
                ('semaine_debut', models.DateField(blank=True, null=True)),
                ('numero_semaine', models.IntegerField(blank=True, help_text='Numéro de la semaine de cours', null=True)),
                ('date_cours', models.DateField(blank=True, help_text='Date exacte du cours', null=True)),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=10)),
                ('creneau', models.CharField(max_length=20)),
                ('salle', models.CharField(blank=True, max_length=50, null=True)),
                ('remarques', models.CharField(blank=True, max_length=255, null=True)),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='attribution.attribution')),
            ],
            options={
                'unique_together': {('attribution', 'annee_academique', 'semaine_debut', 'jour', 'creneau')},
            },
        ),
    ]
