# Generated by Django 6.0 on 2026-01-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organisation_userprofile_organisation'),
        ('attribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='cours_attribution',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours_attributions', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='accounts.organisation', verbose_name='Organisation'),
        ),
    ]
