# Generated by Django 6.0 on 2026-01-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0002_attribution_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='type_horaire',
            field=models.CharField(choices=[('cours', 'Cours'), ('examen', 'Examen')], default='cours', help_text="Type d'horaire : cours ou examen", max_length=10),
        ),
    ]
