# Generated by Django 4.2.15 on 2026-02-05 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_organisation_userprofile_organisation'),
        ('teachers', '0002_teacher_organisation'),
        ('attribution', '0003_scheduleentry_type_horaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementHeuresSupplementaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant à payer')),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taux horaire')),
                ('nombre_heures', models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Nombre d'heures")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut du paiement')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence de paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='attribution.attribution', verbose_name='Attribution')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_heures_sup', to='teachers.teacher', verbose_name='Enseignant')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_heures_sup', to='accounts.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Paiement heures supplémentaires',
                'verbose_name_plural': 'Paiements heures supplémentaires',
                'ordering': ['-date_creation'],
                'unique_together': {('attribution', 'enseignant', 'date_creation')},
            },
        ),
    ]
