# Generated by Django 4.2.15 on 2026-02-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0004_paiementheuressupplementaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='type_charge',
            field=models.CharField(choices=[('Reguliere', 'Régulière'), ('Supplementaire', 'Supplémentaire'), ('Speciale', 'Spéciale')], max_length=15, null=True, verbose_name='Type de charge'),
        ),
    ]
