# Generated by Django 5.0 on 2025-11-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ue', models.CharField(max_length=20)),
                ('intitule_ue', models.CharField(max_length=200)),
                ('intitule_ec', models.CharField(blank=True, max_length=200, null=True)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cmi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='CMI')),
                ('td_tp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TD+TP')),
                ('classe', models.CharField(max_length=100)),
                ('semestre', models.CharField(max_length=20)),
                ('departement', models.CharField(max_length=100)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['code_ue'],
            },
        ),
    ]
