# Generated by Django 6.0 on 2026-01-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code_ue',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
