# Generated by Django 5.0 on 2025-11-06 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reglage', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre de la publication')),
                ('type', models.CharField(choices=[('article', 'Article scientifique'), ('livre', 'Livre'), ('chapitre', 'Chapitre de livre'), ('these', 'Thèse'), ('memoire', 'Mémoire'), ('communication', 'Communication de conférence'), ('rapport', 'Rapport de recherche'), ('autre', 'Autre')], default='article', max_length=50, verbose_name='Type de publication')),
                ('date_publication', models.DateField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('mots_cles', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mots clés')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='Fichier')),
                ('auteurs', models.ManyToManyField(related_name='publications', to='teachers.teacher', verbose_name='Auteurs')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='reglage.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='ArticleScientifique',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('journal', models.CharField(max_length=255, verbose_name='Nom du journal/revue')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='Volume')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro')),
                ('pages', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pages')),
                ('impact_factor', models.FloatField(blank=True, null=True, verbose_name="Facteur d'impact")),
                ('peer_reviewed', models.BooleanField(default=True, verbose_name='À comité de lecture')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOI')),
            ],
            options={
                'verbose_name': 'Article scientifique',
                'verbose_name_plural': 'Articles scientifiques',
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('nom_conference', models.CharField(max_length=255, verbose_name='Nom de la conférence')),
                ('lieu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('publie_dans_actes', models.BooleanField(default=False, verbose_name='Publié dans les actes')),
                ('presentation_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de présentation')),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications',
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('editeur', models.CharField(max_length=255, verbose_name='Éditeur')),
                ('lieu_publication', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de publication')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('nombre_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('edition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Édition')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='These',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('niveau', models.CharField(choices=[('doctorat', 'Doctorat'), ('master', 'Master'), ('licence', 'Licence'), ('autre', 'Autre')], default='doctorat', max_length=50, verbose_name='Niveau')),
                ('universite', models.CharField(max_length=255, verbose_name='Université')),
                ('directeur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Directeur de thèse')),
                ('nombre_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('mention', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mention')),
            ],
            options={
                'verbose_name': 'Thèse/Mémoire',
                'verbose_name_plural': 'Thèses/Mémoires',
            },
            bases=('publications.publication',),
        ),
    ]
