# Generated by Django 5.0 on 2025-11-06 07:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('reglage', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codesemaine', models.CharField(default='S-001', max_length=20, verbose_name='Code semaine')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semaines', to='reglage.semestre', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Semaine académique',
                'verbose_name_plural': 'Semaines académiques',
                'ordering': ['-academic_year', 'codesemaine'],
                'unique_together': {('codesemaine', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name="Nom d'utilisateur")),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('export', 'Exportation'), ('import', 'Importation'), ('print', 'Impression'), ('other', 'Autre')], max_length=20, verbose_name="Type d'action")),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modèle concerné')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name="ID de l'objet")),
                ('object_repr', models.TextField(blank=True, null=True, verbose_name="Représentation de l'objet")),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date et heure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Historique d'action",
                'verbose_name_plural': 'Historique des actions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='tracking_ac_timesta_a815fe_idx'), models.Index(fields=['action_type'], name='tracking_ac_action__900048_idx'), models.Index(fields=['model_name'], name='tracking_ac_model_n_b129b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgressStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('total_hours_done', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total heures effectuées')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_stats', to='courses.course', verbose_name='UE')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_stats', to='teachers.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Statistiques de progression',
                'verbose_name_plural': 'Statistiques de progression',
                'unique_together': {('course', 'teacher', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='TeachingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_done', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Heures effectuées')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('completed', 'Terminé'), ('canceled', 'Annulé'), ('rescheduled', 'Reporté')], default='planned', max_length=20, verbose_name='Statut')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.course', verbose_name='UE')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='teachers.teacher', verbose_name='Enseignant')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='reglage.semainecours', verbose_name='Semaine')),
            ],
            options={
                'verbose_name': "Suivi d'enseignement",
                'verbose_name_plural': 'Suivi des enseignements',
                'ordering': ['-week__annee_academique', 'week__numero_semaine', 'course__code_ue'],
                'unique_together': {('course', 'teacher', 'week')},
            },
        ),
    ]
