# Generated by Django 6.0 on 2026-01-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organisation_userprofile_organisation'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicweek',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_weeks', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='teachingprogress',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_progress', to='accounts.organisation', verbose_name='Organisation'),
        ),
    ]
