# Generated by Django 6.0 on 2026-01-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_academicweek_organisation_and_more'),
        ('tracking', '0002_actionlog_organisation'),
    ]

    operations = [
    ]
