# Generated by Django 5.0 on 2025-11-06 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reglage', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('categorie', models.CharField(choices=[('fourniture', 'Fournitures scolaires'), ('materiel', 'Matériel informatique/Électronique'), ('maintenance', 'Maintenance et réparations'), ('salaire', 'Salaire et primes'), ('deplacement', 'Frais de déplacement'), ('service', 'Services externes'), ('autre', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('beneficiaire', models.CharField(max_length=100, verbose_name='Bénéficiaire')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='N° de référence/facture')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='finances/justificatifs/', verbose_name='Justificatif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.departement', verbose_name='Département')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to='teachers.teacher', verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du rapport')),
                ('periode_debut', models.DateField(verbose_name='Période début')),
                ('periode_fin', models.DateField(verbose_name='Période fin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='finances/signatures/', verbose_name='Signature')),
                ('date_signature', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('rapport_pdf', models.FileField(blank=True, null=True, upload_to='finances/rapports/', verbose_name='Rapport PDF')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de signature'), ('signe', 'Signé'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('chef_departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_reports_signed', to='teachers.teacher', verbose_name='Chef de département')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_reports_created', to='teachers.teacher', verbose_name='Créé par')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglage.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Rapport financier',
                'verbose_name_plural': 'Rapports financiers',
                'ordering': ['-periode_fin'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('categorie', models.CharField(choices=[('salaire', 'Salaire'), ('subvention', 'Subvention'), ('frais_scolarite', 'Frais de scolarité'), ('don', 'Don/Contribution'), ('autre', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='N° de référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.departement', verbose_name='Département')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_created', to='teachers.teacher', verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Revenu',
                'verbose_name_plural': 'Revenus',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date_emprunt', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'emprunt")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('emprunteur', models.CharField(max_length=100, verbose_name='Emprunteur')),
                ('motif', models.TextField(verbose_name='Motif du prêt')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('rembourse', 'Remboursé'), ('retard', 'En retard'), ('annule', 'Annulé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('date_remboursement', models.DateField(blank=True, null=True, verbose_name='Date de remboursement')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant remboursé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.departement', verbose_name='Département')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to='teachers.teacher', verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
                'ordering': ['-date_emprunt'],
            },
        ),
    ]
